# 1. ndArray

### (1) ndArray 생성
- 형식 : numpy.array() 함수에 객체를 인자로 추가하여 생성한다.
- 객체로 파이썬의 리스트를 생성하여 입력하여 자동으로 변환된다.

In [1]:
import numpy as np

In [11]:
# 1차원 배열 생성
list1 = [ 1, 2, 3 ]
array1 = np.array(list1)
print(type(list1), type(array1))

array2 = np.array([4, 5, 6])
print(type(array2))

<class 'list'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
tuple1 = (7, 8, 9)
tarray1 = np.array(tuple1)
print(type(tarray1))

<class 'numpy.ndarray'>


In [13]:
set1 = {1, 3, 5}
sarray = np.array(set1)
print(type(sarray))

<class 'numpy.ndarray'>


In [14]:
print(array1, tarray1, sarray)

[1 2 3] [7 8 9] {1, 3, 5}


### (3) dtype
- 저장된 데이터 타입 확인
- 모든 데이터 타입이 동일해야 함

In [20]:
# 정수 배열
arr_int = np.array([1, 2, 3])
print(type(arr_int))
print(arr_int.dtype)

<class 'numpy.ndarray'>
int64


In [23]:
# 실수 배열 
arr_float = np.array([1.23, 2.09, 2.601])
print(type(arr_float))
print(arr_float.dtype)

<class 'numpy.ndarray'>
float64


In [24]:
arr_str = np.array(['a', 'b', 'c'])
print(type(arr_str))
print(arr_str.dtype)

<class 'numpy.ndarray'>
<U1


### (4) 자동 형변환
- 여러 타입이 저장되는 경우 가장 큰 타입으로 자동 변환

In [25]:
# 정수 + 문자열이 같이 저장되어 있는 경우
arr = np.array([1, 2, 'abc'])
arr

array(['1', '2', 'abc'], dtype='<U21')

In [26]:
# 정수 + 실수
arr = np.array([1, 2, 3.1415])
arr

array([1.    , 2.    , 3.1415])

In [28]:
# 실수 + 문자열 => 정수 < 실수 < 문자열
arr = np.array([1.0, 2.12, 'abc'])
arr

array(['1.0', '2.12', 'abc'], dtype='<U32')

### (5) 데이터 타입 변환 - astype()
- 데이터 타입을 명시적으로 변환
- 자주 사용하는 dtype 종류
|dtype|설명|메모리|
|-----|----|------|
|int32|32bit 정수|4byte|
|int64|64bit 정수(기본값)|8byte|
|float32|32bit 실수|4byte|
|float64|64bit 실수(기본값)|8byte|
|bool|불린 (True/False)|1byte|
|<U숫자|유니코드 문자열|가변|

In [29]:
arr_int = np.array([1, 2, 3])
arr_int.dtype

dtype('int64')

In [32]:
# arr_int 배열을 float64 타입의 배열로 변환
arr_float = arr_int.astype('float64')
arr_float.dtype
arr_float

array([1., 2., 3.])

In [33]:
# arr_float 배열을 int32 타입의 배열로 변환
arr_int32 = arr_float.astype('int32')
arr_int32.dtype
arr_int32

array([1, 2, 3], dtype=int32)

In [35]:
# arr_int32 배열을 문자열 배열로 변환
arr_str = arr_int32.astype('<U1')
arr_str

array(['1', '2', '3'], dtype='<U1')

### (6) 데이터 생성 함수
- np.aragne(start, end, step)
- Python의 range() 함수와 유사하며, 연속된 데이터를 생성한다

In [36]:
# 0 ~ 9까지 데이터 생성
num = np.arange(0, 10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# 0~1 까지 0.2만큼씩 증가
num = np.arange(0, 1.2, 0.2)
num

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### (7) np.zeros(), np.ones()
- 모든 데이터가 0인 배열 : np.zeros()
- 모든 데이터가 1인 배열 : np.ones()

In [41]:
arr_zeros = np.zeros((3,))
arr_zeros

array([0., 0., 0.])

In [44]:
# 3행의 1차원 배열 생성 후, 모든 데이터를 0으로 초기화
arr_zeros = np.zeros((3,), 'int64')
arr_zeros

array([0, 0, 0])

In [47]:
# 모든 데이터를 0으로 갖는 3행 4열의 2차원 배열 생성
arr_zeros = np.zeros((3, 4), dtype='int64')
arr_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
# 모든 원소를 정수 1로 가지는 5행의 1차원 배열 생성
arr_ones = np.ones((5,), dtype="int64")
arr_ones

array([1, 1, 1, 1, 1])

In [49]:
# 모든 원소를 실수 1로 가지는 2행 5열의 2차원 배열 생성
arr_ones2 = np.ones((2, 5), dtype="float64")
arr_ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### (8) np.linspace()
- np.linspace(start, end, number)
- 시작과 끝 사이의 값을 균등하게 나누어 배열 생성

In [50]:
arr_lin = np.linspace(1, 5, 5)
arr_lin

array([1., 2., 3., 4., 5.])

### (9) np.random
- 0과 1사이의 난수를 발생
- rand(shape) 함수를 이용하여 실수형 배열 생성
- randint(high, size = shape) 함수를 이용하여 정수형 배열 생성

In [64]:
arr_random = np.random.rand(3)
print(arr_random)

[0.87656145 0.5930292  0.02373693]


In [65]:
# 난수를 발생하여 5행 4열의 2차원 배열 생성
arr_rando = np.random.rand(5, 4)
arr_rando

array([[0.64946454, 0.61791735, 0.27206059, 0.8593149 ],
       [0.90505137, 0.99383043, 0.88443091, 0.6339285 ],
       [0.05126719, 0.63672212, 0.61108257, 0.02669165],
       [0.96253358, 0.83256677, 0.53794454, 0.08054493],
       [0.13103113, 0.04664054, 0.1952563 , 0.46825618]])

In [67]:
# 난수를 발생하여 5보다 작은 정수들만, 3행의 1차원 배열 생성
arr_random = np.random.randint(5, size=(3,))
arr_random

array([2, 3, 2], dtype=int32)

In [69]:
# 난수를 발생하여 10보다 작은 정수들만, 3행 5열의 2차원 배열 생성
arr_random = np.random.randint(10, size=(3, 5))
arr_random

array([[5, 0, 0, 6, 5],
       [2, 6, 3, 0, 9],
       [4, 8, 4, 4, 0]], dtype=int32)

### (10) axis - 배열의 축
- 2차원 배열의 axis=0은 row(행), axis=1 column(컬럼) 방향을 의미

In [75]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

In [77]:
# 행(가로) 기준으로 합계 계산
arr_row_sum = np.sum(arr, axis=0)
print(arr_row_sum)

[5 7 9]


In [78]:
# 컬럼(세로) 기준으로 합계 게산
arr_col_sum = np.sum(arr, axis=1)
print(arr_col_sum)

[ 6 15]


### (11) reshape()
- 배열의 형태를 바꾸는 함수
- 배열의 우너소 개수를 유지하면서 변환해야 함 - 부족하면 value Error 발생함!

In [79]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# 1차원 arr 객체를 2행 5열의 2차원 배열로 변환
np.reshape(arr, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
arr2 = np.reshape(arr, (2, 5))
print(arr2.shape)
print(arr2)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [86]:
# 2행 5열의 2차원 배열을 1차원 배열로 변환
arr3 = np.reshape(arr2, (10,))
print(arr3.shape)
print(arr3)

(10,)
[0 1 2 3 4 5 6 7 8 9]


In [97]:
arr4 = np.arange(16).reshape((4,4))
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
arr5 = np.reshape(arr4, (2, 8))
print(arr5.shape)
print(arr5)

(2, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [102]:
# 5열의 2차원 배열로 생성 - 컬럼은 고정, 행은 자동계산 (-1_
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
arr7 = np.reshape(arr6, (-1, 5))
print(arr7.shape)
print(arr7)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [104]:
# 2행의 2차원 배열로 생성 - 컬럼은 자동계산(-1), 해은 2행 고정
arr8 = np.reshape(arr6, (2, -1))
print(arr8.shape)
print(arr8)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [108]:
# 원소 갯수 256개 2컬럼을 가진 2차원 배열 생성
arr10 = np.arange(256).reshape((-1, 2))
print(arr10.shape)

(128, 2)


In [109]:
# 8개의 원소를 가진 1차원 배열 => 3차원 배열로 변환
arr_3d = np.arange(8).reshape((2, 2, 2))
print(arr_3d.shape)
print(arr_3d)

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [111]:
# 3차원 배열 1차원으로 변환
arr_1d = np.reshape(arr_3d, (-1,))
print(arr_1d)
print(arr_1d.shape)

[0 1 2 3 4 5 6 7]
(8,)


### (12) 

In [173]:
arr1 = np.arange(10, 60, 10)
print(arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2.shape)

print(f"arr1 정보 : {arr1.shape}, {arr1.dtype}, {arr1.ndim}")
print(f"arr2 정보 : {arr2.shape}, {arr2.dtype}, {arr2.ndim}")

[10 20 30 40 50]
(3, 3)
arr1 정보 : (5,), int64, 1
arr2 정보 : (3, 3), int64, 2


In [160]:
arr3 = np.arange(0, 20)
print(arr3.shape)
print(arr3)

arr3_2d = np.reshape(arr3, (4, 5))
print(arr3_2d)

arr4 = np.zeros((3, 4), dtype='int32')
print(arr4)

arr5 = np.arange(0, 1, 2)
print(arr5)

(20,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[0.  0.2 0.4 0.6 0.8 1. ]
